/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AffiliatesBpnlConstraint = AffiliatesBpnlConstraint1;
export type BpnlRightOperand = string;

export interface AffiliatesBpnlConstraint1 {
  leftOperand?: 'AffiliatesBpnl';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [BpnlRightOperand, ...BpnlRightOperand[]];
}
