/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AffiliatesRegionConstraintSchema = AffiliatesRegionConstraint;

export interface AffiliatesRegionConstraint {
  leftOperand?: 'AffiliatesRegion';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | RegionAllRightOperand
      | RegionEuropeRightOperand
      | RegionNorthAmericaRightOperand
      | RegionSouthAmericaRightOperand
      | RegionAfricaRightOperand
      | RegionAsiaRightOperand
      | RegionOceaniaRightOperand
      | RegionAntarcticaRightOperand
    ),
    ...(
      | RegionAllRightOperand
      | RegionEuropeRightOperand
      | RegionNorthAmericaRightOperand
      | RegionSouthAmericaRightOperand
      | RegionAfricaRightOperand
      | RegionAsiaRightOperand
      | RegionOceaniaRightOperand
      | RegionAntarcticaRightOperand
    )[]
  ];
}
export interface RegionAllRightOperand {
  const?: 'cx.region.all:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC).";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use to its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies'), unless the Parties have otherwise agreed on a right of sublicensing in the referenced contract (cx-policy:ContractReference).";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionEuropeRightOperand {
  const?: 'cx.region.europe:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in Europe.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in Europe, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionNorthAmericaRightOperand {
  const?: 'cx.region.northAmerica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in North America.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in North America, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionSouthAmericaRightOperand {
  const?: 'cx.region.southAmerica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in South America.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in South America, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionAfricaRightOperand {
  const?: 'cx.region.africa:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in Africa.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in Africa, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionAsiaRightOperand {
  const?: 'cx.region.asia:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in Asia.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in Asia, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionOceaniaRightOperand {
  const?: 'cx.region.oceania:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in Oceania.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in Oceania, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface RegionAntarcticaRightOperand {
  const?: 'cx.region.antarctica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing'), provided that the Data Consumer ensures that its Affiliated Companies comply with the terms of this Agreement concluded via the Registered Connector (RC). The registered offices of the relevant Affiliated Companies must be located in Antarctica.";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by its affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') that are domiciled in Antarctica, unless the Parties have otherwise agreed on a right of sublicensing (either in full or with respect to individual Affiliated Companies) in the referenced bilateral contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
