/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AffiliatesBpnlConstraint = AffiliatesBpnlConstraint1;

export interface AffiliatesBpnlConstraint1 {
  leftOperand?: 'AffiliatesBpnl';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [BpnlRightOperand, ...BpnlRightOperand[]];
}
export interface BpnlRightOperand {
  pattern?: '^BPNL[0-9A-Z]{12}$';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by the Affiliated companies within the meaning of Section 15 German Stock Corporation Act ('Affiliated Companies') ('Sublicensing') specified herein, provided that the Data Consumer ensures that such companies and/or its its Affiliated Companies comply with the terms of the Agreement concluded via the Registered Connector (RC).";
    prohibition?: "The Data Consumer is not entitled to make the Data available for use by the companies specified herein ('Sublicensing'), unless the Parties have otherwise agreed on a right to sublicense the Data (either in full or with respect to individual affiliated companies) in the referenced  contract ('cx-policy:ContractReference') or have agreed to this separately.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
