/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AffiliatesRegionConstraintSchema = AffiliatesRegionConstraint;
export type RegionAllRightOperand = 'cx.region.all:1';
export type RegionEuropeRightOperand = 'cx.region.europe:1';
export type RegionNorthAmericaRightOperand = 'cx.region.northAmerica:1';
export type RegionSouthAmericaRightOperand = 'cx.region.southAmerica:1';
export type RegionAfricaRightOperand = 'cx.region.africa:1';
export type RegionAsiaRightOperand = 'cx.region.asia:1';
export type RegionOceaniaRightOperand = 'cx.region.oceania:1';
export type RegionAntarcticaRightOperand = 'cx.region.antarctica:1';

export interface AffiliatesRegionConstraint {
  leftOperand?: 'AffiliatesRegion';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | RegionAllRightOperand
      | RegionEuropeRightOperand
      | RegionNorthAmericaRightOperand
      | RegionSouthAmericaRightOperand
      | RegionAfricaRightOperand
      | RegionAsiaRightOperand
      | RegionOceaniaRightOperand
      | RegionAntarcticaRightOperand
    ),
    ...(
      | RegionAllRightOperand
      | RegionEuropeRightOperand
      | RegionNorthAmericaRightOperand
      | RegionSouthAmericaRightOperand
      | RegionAfricaRightOperand
      | RegionAsiaRightOperand
      | RegionOceaniaRightOperand
      | RegionAntarcticaRightOperand
    )[]
  ];
}
