/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type BusinessPartnerNumberConstraintSchema = BusinessPartnerNumberConstraint;
export type BusinessPartnerNumberRightOperand = string;

export interface BusinessPartnerNumberConstraint {
  leftOperand?: 'BusinessPartnerNumber';
  operator?: 'isAnyOf' | 'isNoneOf';
  /**
   * @minItems 1
   */
  rightOperand?: [BusinessPartnerNumberRightOperand, ...BusinessPartnerNumberRightOperand[]];
}
