/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConfidentialInformationMeasuresConstraintSchema = ConfidentialInformationMeasuresConstraint;

export interface ConfidentialInformationMeasuresConstraint {
  leftOperand?: 'ConfidentialInformationMeasures';
  operator?: 'eq';
  rightOperand?: ConfidentialityMeasuresRightOperand;
}
export interface ConfidentialityMeasuresRightOperand {
  const?: 'cx.confidentiality.measures:1';
  legalText?: {
    permission?: 'The Data Consumer is obliged to take all appropriate technical and organisational measures to protect the Confidential Information of the Data Provider, in order to prevent unauthorised disclosure to third parties. The Data Consumer is also obliged to inform the Data Provider without undue delay about any unauthorised disclosure of Confidential Information.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
