/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConfidentialInformationSharingConstraintSchema = ConfidentialInformationSharingConstraint;
export type SharingAffiliatesRightOperand = 'cx.sharing.affiliates:1';
export type SharingManagedLegalEntityRightOperand = 'cx.sharing.managedLegalEntity:1';

export interface ConfidentialInformationSharingConstraint {
  leftOperand?: 'ConfidentialInformationSharing';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    SharingAffiliatesRightOperand | SharingManagedLegalEntityRightOperand,
    ...(SharingAffiliatesRightOperand | SharingManagedLegalEntityRightOperand)[]
  ];
}
