/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ConfidentialInformationSharingConstraintSchema = ConfidentialInformationSharingConstraint;

export interface ConfidentialInformationSharingConstraint {
  leftOperand?: 'ConfidentialInformationSharing';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    SharingAffiliatesRightOperand | SharingManagedLegalEntityRightOperand,
    ...(SharingAffiliatesRightOperand | SharingManagedLegalEntityRightOperand)[]
  ];
}
export interface SharingAffiliatesRightOperand {
  const?: 'cx.sharing.affiliates:1';
  legalText?: {
    permission?: "The Data Consumer may only disclose Confidential Information to Affiliated Companies if and to the extent that the Data Provider has expressly permitted such disclosure in accordance with the Data Exchange Governance or the cx-policy:affiliates.*. The Data Consumer may only disclose Confidential Information to Affiliated Companies to the extent that the Affiliated Companies and their employees are bound to Confidentiality Obligations at least equivalent to those set forth in this Agreement. Furthermore, access to and use of the relevant Data must be restricted to those employees of the Affiliated Company who require the Data in order to exercise the agreed usage rights ('need to know').";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface SharingManagedLegalEntityRightOperand {
  const?: 'cx.sharing.managedLegalEntity:1';
  legalText?: {
    permission?: "The Data Consumer may only disclose Confidential Information to those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') if and to the extent those companies are expressly listed in cx-policy:managedLegalEntity.*. The Data Consumer may only disclose Confidential Information to those Companies to the extent that those Companies and their employees are bound to Confidentiality Obligations at least equivalent to those set forth in this Agreement. Furthermore, access to and use of the relevant Data must be restricted to those employees of the Company who require the Data in order to exercise the agreed usage rights ('need to know').";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
