/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractReferenceConstraintSchema = ContractReferenceConstraint;

export interface ContractReferenceConstraint {
  leftOperand?: 'ContractReference';
  operator?: 'isAllOf';
  /**
   * @minItems 1
   */
  rightOperand?: [ContractReferenceRightOperand, ...ContractReferenceRightOperand[]];
}
export interface ContractReferenceRightOperand {
  legalText?: {
    permission?: 'Data Provider and Data Consumer are free to reference an existing, individual contract as a basis of the Agreement concluded via the Registered Connector (RC). This can be a framework agreement or a very specific contract. The rightOperand value for this constraint can be a free to choose reference under which both parties are able to identify their contract. The reference does not have to have a version number.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
