/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractTerminationConstraintSchema = ContractTerminationConstraint;
export type DataDeletionRightOperand = 'cx.data.deletion:1';
export type DataKeepingRightOperand = 'cx.data.keeping:1';

export interface ContractTerminationConstraint {
  leftOperand?: 'ContractTermination';
  operator?: 'eq';
  rightOperand?: DataDeletionRightOperand | DataKeepingRightOperand;
}
