/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataUsageEndDefinitionConstraintSchema = DataUsageEndDefinitionConstraint;
export type DataUsageEndDefinitionRightOperand = 'cx.dataUsageEnd.unlimited:1';

export interface DataUsageEndDefinitionConstraint {
  leftOperand?: 'DataUsageEndDefinition';
  operator?: 'eq';
  rightOperand?: DataUsageEndDefinitionRightOperand;
}
