/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataUsageEndDateConstraintSchema = DataUsageEndDateConstraint;

export interface DataUsageEndDateConstraint {
  leftOperand?: 'DataUsageEndDate';
  operator?: 'eq';
  rightOperand?: DataUsageEndDateRightOperand;
}
export interface DataUsageEndDateRightOperand {
  pattern?: '^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(Z|[+-]\\d{2}:\\d{2}))$';
  legalText?: {
    permission?: 'The Data Provider shall make the Data available with a usage period permitted until the end date specified herein, in accordance with the usage conditions specified in cx-policy:UsagePurpose, commencing from the second the Agreement is concluded via the Registered Connector (RC). Upon expiry of the usage period, the Data Consumer shall no longer be entitled to use the Data and shall delete the Data in order to prevent any further Use, unless the Data Consumer has received the same Data under another still valid contract. The Agreement shall terminate upon expiry of the usage period of the Data without the need for a separate notice of termination.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
