/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataFrequencyConstraintSchema = DataFrequencyConstraint;
export type DataFrequencyOnceRightOperand = 'cx.dataFrequency.once:1';
export type DataFrequencyUnlimitedRightOperand = 'cx.dataFrequency.unlimited:1';

export interface DataFrequencyConstraint {
  leftOperand?: 'DataFrequency';
  operator?: 'eq';
  rightOperand?: DataFrequencyOnceRightOperand | DataFrequencyUnlimitedRightOperand;
}
