/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvisioningEndDurationDaysConstraintSchema = DataProvisioningEndDurationDaysConstraint;

export interface DataProvisioningEndDurationDaysConstraint {
  leftOperand?: 'DataProvisioningEndDurationDays';
  operator?: 'eq';
  rightOperand?: DataProvisioningEndDurationDaysRightOperand;
}
export interface DataProvisioningEndDurationDaysRightOperand {
  legalText?: {
    obligation?: 'The Data Provider shall make the Data available for the period specified herein in days, commencing from the second the Agreement is concluded via the Registered Connector (RC).';
    [k: string]: unknown;
  };
  operandType?: 'integer';
}
