/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvisioningEndDurationDaysConstraintSchema = DataProvisioningEndDurationDaysConstraint;
export type DataProvisioningEndDurationDaysRightOperand = number;

export interface DataProvisioningEndDurationDaysConstraint {
  leftOperand?: 'DataProvisioningEndDurationDays';
  operator?: 'eq';
  rightOperand?: DataProvisioningEndDurationDaysRightOperand;
}
