/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataUsageEndDurationDaysConstraintSchema = DataUsageEndDurationDaysConstraint;

export interface DataUsageEndDurationDaysConstraint {
  leftOperand?: 'DataUsageEndDurationDays';
  operator?: 'eq';
  rightOperand?: DataUsageEndDurationDaysRightOperand;
}
export interface DataUsageEndDurationDaysRightOperand {
  legalText?: {
    permission?: 'The Data Provider shall make the Data available for the usage period specified herein, measured in days, in accordance with the usage conditions set out in cx-policy:UsagePurpose, commencing from the moment of concluding the Agreement via the Registered Connector (RC). Upon expiry of the permitted usage period, the Data Consumer shall no longer be entitled to use the Data, and shall delete the Data from all systems and storage media in order to prevent any further use, unless the Data Consumer has received the same Data under another valid contract. The Agreement shall terminate automatically upon expiry of the usage period for the Data, without the need for a separate notice of termination.';
    [k: string]: unknown;
  };
  operandType?: 'integer';
}
