/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataUsageEndDefinitionConstraintSchema = DataUsageEndDefinitionConstraint;

export interface DataUsageEndDefinitionConstraint {
  leftOperand?: 'DataUsageEndDefinition';
  operator?: 'eq';
  rightOperand?: DataUsageEndDefinitionRightOperand;
}
export interface DataUsageEndDefinitionRightOperand {
  const?: 'cx.dataUsageEnd.unlimited:1';
  legalText?: {
    permission?: 'The Data Provider shall make the Data available for an unlimited period of use in accordance with the usage conditions specified in cx-policy:UsagePurpose, commencing from the second the Agreement is concluded via the Registered Connector (RC).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
