/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvisioningEndDateConstraintSchema = DataProvisioningEndDateConstraint;
export type DataProvisioningEndDateRightOperand = string;

export interface DataProvisioningEndDateConstraint {
  leftOperand?: 'DataProvisioningEndDate';
  operator?: 'eq';
  rightOperand?: DataProvisioningEndDateRightOperand;
}
