/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataProvisioningEndDateConstraintSchema = DataProvisioningEndDateConstraint;

export interface DataProvisioningEndDateConstraint {
  leftOperand?: 'DataProvisioningEndDate';
  operator?: 'eq';
  rightOperand?: DataProvisioningEndDateRightOperand;
}
export interface DataProvisioningEndDateRightOperand {
  pattern?: '^(\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(Z|[+-]\\d{2}:\\d{2}))$';
  legalText?: {
    obligation?: 'The Data Provider shall make the Data available for a limited period until the end date specified herein, commencing from the second the Agreement is concluded via the Registered Connector (RC).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
