/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataUsageEndDateConstraintSchema = DataUsageEndDateConstraint;
export type DataUsageEndDateRightOperand = string;

export interface DataUsageEndDateConstraint {
  leftOperand?: 'DataUsageEndDate';
  operator?: 'eq';
  rightOperand?: DataUsageEndDateRightOperand;
}
