/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type DataFrequencyConstraintSchema = DataFrequencyConstraint;

export interface DataFrequencyConstraint {
  leftOperand?: 'DataFrequency';
  operator?: 'eq';
  rightOperand?: DataFrequencyOnceRightOperand | DataFrequencyUnlimitedRightOperand;
}
export interface DataFrequencyOnceRightOperand {
  const?: 'cx.dataFrequency.once:1';
  legalText?: {
    permission?: 'This Agreement concluded via the Registered Connector (RC). applies both to a one-time, time-limited data exchange as well as to sequential data exchanges under similar conditions, potentially also in varying quantities (Data as a Service).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface DataFrequencyUnlimitedRightOperand {
  const?: 'cx.dataFrequency.unlimited:1';
  legalText?: {
    permission?: 'This Agreement concluded via the Registered Connector (RC). applies to the multiple or repeated exchange of similar Data at different times and in different quantities within the scope of the selected Use Case.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
