/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExclusiveUsageConstraintSchema = ExclusiveUsageConstraint;

export interface ExclusiveUsageConstraint {
  leftOperand?: 'ExclusiveUsage';
  operator?: 'eq';
  rightOperand?: ExclusiveUsageDataConsumerRightOperand;
}
export interface ExclusiveUsageDataConsumerRightOperand {
  const?: 'cx.exclusiveUsage.dataConsumer:1';
  legalText?: {
    permission?: 'The Data Consumer has the exclusive right to use the Data within the scope of the agreed purposes (cx-policy:UsagePurpose). The Data Provider’s right to use the Data it has provided for its own internal purposes remains unaffected.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
