/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExclusiveUsageConstraintSchema = ExclusiveUsageConstraint;
export type ExclusiveUsageDataConsumerRightOperand = 'cx.exclusiveUsage.dataConsumer:1';

export interface ExclusiveUsageConstraint {
  leftOperand?: 'ExclusiveUsage';
  operator?: 'eq';
  rightOperand?: ExclusiveUsageDataConsumerRightOperand;
}
