/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FrameworkAgreementConstraintSchema = FrameworkAgreementConstraint;
export type DataExchangeGovernanceRightOperand = 'DataExchangeGovernance:2.0';

export interface FrameworkAgreementConstraint {
  leftOperand?: 'FrameworkAgreement';
  operator?: 'eq';
  rightOperand?: DataExchangeGovernanceRightOperand;
}
