/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JurisdictionLocationReferenceConstraintSchema = JurisdictionLocationReferenceConstraint;

export interface JurisdictionLocationReferenceConstraint {
  leftOperand?: 'JurisdictionLocationReference';
  operator?: 'eq';
  rightOperand?: LocationDataConsumerRightOperand | LocationContractReferenceRightOperand;
}
export interface LocationDataConsumerRightOperand {
  const?: 'cx.location.dataConsumer:1';
  legalText?: {
    permission?: 'The exclusive venue for all disputes arising from the contract concluded via the Registered Connector (RC) shall be at the competent court at the registered office of the Data Consumer.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface LocationContractReferenceRightOperand {
  const?: 'cx.location.contractReference:1';
  legalText?: {
    permission?: 'The exclusive venue for all disputes arising from the Agreement concluded via the Registered Connector (RC) shall correspond to the venue specified in the referenced contract (as referenced in cx-policy:ContractReference).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
