/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JurisdictionLocationReferenceConstraintSchema = JurisdictionLocationReferenceConstraint;
export type LocationDataConsumerRightOperand = 'cx.location.dataConsumer:1';
export type LocationContractReferenceRightOperand = 'cx.location.contractReference:1';

export interface JurisdictionLocationReferenceConstraint {
  leftOperand?: 'JurisdictionLocationReference';
  operator?: 'eq';
  rightOperand?: LocationDataConsumerRightOperand | LocationContractReferenceRightOperand;
}
