/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type JurisdictionLocationConstraintSchema = JurisdictionLocationConstraint;

export interface JurisdictionLocationConstraint {
  leftOperand?: 'JurisdictionLocation';
  operator?: 'eq';
  rightOperand?: LocationStringRightOperand;
}
export interface LocationStringRightOperand {
  legalText?: {
    permission?: 'The exclusive venue for all disputes arising from the Agreement concluded via the Registered Connector (RC) shall be at the competent court at the location specified herein.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
