/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LiabilityConstraintConstraintSchema = LiabilityConstraint;

export interface LiabilityConstraint {
  leftOperand?: 'Liability';
  operator?: 'eq';
  rightOperand?: GrossNegligenceRightOperand | SlightNegligenceRightOperand;
}
export interface GrossNegligenceRightOperand {
  const?: 'cx.grossNegligence:1';
  legalText?: {
    permission?: "The Data Provider's liability is limited to intent and gross negligence. The same applies in regard to the Data Provider's liability for its legal representatives, employees and authorised representatives.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface SlightNegligenceRightOperand {
  const?: 'cx.slightNegligence:1';
  legalText?: {
    permission?: 'The liability of the Data Provider in cases of ordinary negligence shall be limited to x, as individually agreed by the Parties in the referenced bilateral agreement (cx-policy:ContractReference). The foregoing limitation of liability shall not apply in the event of mandatory statutory liability (in particular under the German Product Liability Act), nor in the event of the assumption of a guarantee or for any culpably caused bodily injury.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
