/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ManagedLegalEntityBpnlConstraintSchema = ManagedLegalEntityBpnlConstraint;

export interface ManagedLegalEntityBpnlConstraint {
  leftOperand?: 'ManagedLegalEntityBpnl';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [ManagedLegalEntityBpnlRightOperand, ...ManagedLegalEntityBpnlRightOperand[]];
}
export interface ManagedLegalEntityBpnlRightOperand {
  pattern?: '^BPNL[0-9A-Z]{12}$';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use to the companies specified herein ('Sublicensing'), for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard CX-0074), provided that the Data Consumer ensures that such managed companies comply with the terms of the Agreement concluded via the Registered Connector (RC).";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
