/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ManagedLegalEntityRegionConstraintSchema = ManagedLegalEntityRegionConstraint;

export interface ManagedLegalEntityRegionConstraint {
  leftOperand?: 'ManagedLegalEntityRegion';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | ManagedLegalEntityRegionAllRightOperand
      | ManagedLegalEntityRegionEuropeRightOperand
      | ManagedLegalEntityRegionNorthAmericaRightOperand
      | ManagedLegalEntityRegionSouthAmericaRightOperand
      | ManagedLegalEntityRegionAfricaRightOperand
      | ManagedLegalEntityRegionAsiaRightOperand
      | ManagedLegalEntityRegionOceaniaRightOperand
      | ManagedLegalEntityRegionAntarcticaRightOperand
    ),
    ...(
      | ManagedLegalEntityRegionAllRightOperand
      | ManagedLegalEntityRegionEuropeRightOperand
      | ManagedLegalEntityRegionNorthAmericaRightOperand
      | ManagedLegalEntityRegionSouthAmericaRightOperand
      | ManagedLegalEntityRegionAfricaRightOperand
      | ManagedLegalEntityRegionAsiaRightOperand
      | ManagedLegalEntityRegionOceaniaRightOperand
      | ManagedLegalEntityRegionAntarcticaRightOperand
    )[]
  ];
}
export interface ManagedLegalEntityRegionAllRightOperand {
  const?: 'cx.region.all:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC).";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionEuropeRightOperand {
  const?: 'cx.region.europe:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in Europe.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionNorthAmericaRightOperand {
  const?: 'cx.region.northAmerica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in North America.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionSouthAmericaRightOperand {
  const?: 'cx.region.southAmerica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in South America.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionAfricaRightOperand {
  const?: 'cx.region.africa:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in Africa.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionAsiaRightOperand {
  const?: 'cx.region.asia:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in Asia.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionOceaniaRightOperand {
  const?: 'cx.region.oceania:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in Oceania.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface ManagedLegalEntityRegionAntarcticaRightOperand {
  const?: 'cx.region.antarctica:1';
  legalText?: {
    permission?: "The Data Provider permits the Data Consumer to make the Data available for use by those companies for which the Data Consumer acts in an 'is managed by' relationship (within the meaning of the Catena-X Standard 'CX-0074') ('Sublicensing'), provided that the Data Consumer ensures that such companies comply with the terms of the Agreement concluded via the Registered Connector (RC). The registered offices of such managed companies must be located in Antarctica.";
    [k: string]: unknown;
  };
  operandType?: 'string';
}
