/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ManagedLegalEntityRegionConstraintSchema = ManagedLegalEntityRegionConstraint;
export type ManagedLegalEntityRegionAllRightOperand = 'cx.region.all:1';
export type ManagedLegalEntityRegionEuropeRightOperand = 'cx.region.europe:1';
export type ManagedLegalEntityRegionNorthAmericaRightOperand = 'cx.region.northAmerica:1';
export type ManagedLegalEntityRegionSouthAmericaRightOperand = 'cx.region.southAmerica:1';
export type ManagedLegalEntityRegionAfricaRightOperand = 'cx.region.africa:1';
export type ManagedLegalEntityRegionAsiaRightOperand = 'cx.region.asia:1';
export type ManagedLegalEntityRegionOceaniaRightOperand = 'cx.region.oceania:1';
export type ManagedLegalEntityRegionAntarcticaRightOperand = 'cx.region.antarctica:1';

export interface ManagedLegalEntityRegionConstraint {
  leftOperand?: 'ManagedLegalEntityRegion';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | ManagedLegalEntityRegionAllRightOperand
      | ManagedLegalEntityRegionEuropeRightOperand
      | ManagedLegalEntityRegionNorthAmericaRightOperand
      | ManagedLegalEntityRegionSouthAmericaRightOperand
      | ManagedLegalEntityRegionAfricaRightOperand
      | ManagedLegalEntityRegionAsiaRightOperand
      | ManagedLegalEntityRegionOceaniaRightOperand
      | ManagedLegalEntityRegionAntarcticaRightOperand
    ),
    ...(
      | ManagedLegalEntityRegionAllRightOperand
      | ManagedLegalEntityRegionEuropeRightOperand
      | ManagedLegalEntityRegionNorthAmericaRightOperand
      | ManagedLegalEntityRegionSouthAmericaRightOperand
      | ManagedLegalEntityRegionAfricaRightOperand
      | ManagedLegalEntityRegionAsiaRightOperand
      | ManagedLegalEntityRegionOceaniaRightOperand
      | ManagedLegalEntityRegionAntarcticaRightOperand
    )[]
  ];
}
