/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PrecedenceConstraintSchema = PrecedenceConstraint;

export interface PrecedenceConstraint {
  leftOperand?: 'Precedence';
  operator?: 'eq';
  rightOperand?: PrecedenceContractReferenceRightOperand | PrecedenceRcAgreementRightOperand;
}
export interface PrecedenceContractReferenceRightOperand {
  const?: 'cx.precedence.contractReference:1';
  legalText?: {
    permission?: 'The Parties are free to agree on additional provisions in a separately referenced contract, in addition to the arrangements made via the Registered Connector (RC) Process (referenced in leftOperand: contractReference). In the event of any conflict between the provisions agreed via the RC Process and those of the referenced contract, the provisions of the contract shall take precedence.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface PrecedenceRcAgreementRightOperand {
  const?: 'cx.precedence.rcAgreement:1';
  legalText?: {
    permission?: 'The Parties are free to agree on additional provisions in a referenced contract (as referenced in leftOperand: contractReference) in addition to the arrangements agreed via the Registered Connector (RC) Process. In such case, the provisions agreed via the RC Process shall take precedence over the provisions of the referenced contract.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
