/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PrecedenceConstraintSchema = PrecedenceConstraint;
export type PrecedenceContractReferenceRightOperand = 'cx.precedence.contractReference:1';
export type PrecedenceRcAgreementRightOperand = 'cx.precedence.rcAgreement:1';

export interface PrecedenceConstraint {
  leftOperand?: 'Precedence';
  operator?: 'eq';
  rightOperand?: PrecedenceContractReferenceRightOperand | PrecedenceRcAgreementRightOperand;
}
