/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UsagePurposeConstraintSchema = UsagePurposeConstraint;
export type CoreLegalRequirementForThirdPartyRightOperand = 'cx.core.legalRequirementForThirdparty:1';
export type CoreIndustrycoreRightOperand = 'cx.core.industrycore:1';
export type CoreQualityNotificationsRightOperand = 'cx.core.qualityNotifications:1';
export type CoreDigitalTwinRegistry = 'cx.core.digitalTwinRegistry:1';
export type PfcBaseRightOperand = 'cx.pcf.base:1';
export type QualityBaseRightOperand = 'cx.quality.base:1';
export type DcmBaseRightOperand = 'cx.dcm.base:1';
export type PurisBaseRightOperand = 'cx.puris.base:1';
export type CircularDppRightOperand = 'cx.circular.dpp:1';
export type CircularSmcRightOperand = 'cx.circular.smc:1';
export type CircularMarketplaceRightOperand = 'cx.circular.marketplace:1';
export type CircularMaterialaccountingRightOperand = 'cx.circular.materialaccounting:1';
export type BpdmGateUploadRightOperand = 'cx.bpdm.gate.upload:1';
export type BpdmGateDownloadRightOperand = 'cx.bpdm.gate.download:1';
export type BpdmPoolRightOperand = 'cx.bpdm.pool:1';
export type BpdmVasDataqualityUploadRightOperand = 'cx.bpdm.vas.dataquality.upload:1';
export type BpdmVasDataqualityDownloadRightOperand = 'cx.bpdm.vas.dataquality.download:1';
export type BpdmVasCountryrisk = 'cx.bpdm.vas.countryrisk:1';
export type BpdmVasBdvUploadRightOperand = 'cx.bpdm.vas.bdv.upload:1';
export type BpdmVasFpdUploadRightOperand = 'cx.bpdm.vas.fpd.upload:1';
export type BpdmVasFpdDownloadRightOperand = 'cx.bpdm.vas.fpd.download:1';
export type BpdmVasSwdUploadRightOperand = 'cx.bpdm.vas.swd.upload:1';
export type BpdmVasSwdDownloadRightOperand = 'cx.bpdm.vas.swd.download:1';
export type BpdmVasNpsUploadRightOperand = 'cx.bpdm.vas.nps.upload:1';
export type BpdmVasNpsDownloadRightOperand = 'cx.bpdm.vas.nps.download:1';
export type CcmBaseRightOperand = 'cx.ccm.base:1';
export type BpdmPoolAllRightOperand = 'cx.bpdm.poolAll:1';
export type LogisticsBaseRightOperand = 'cx.logistics.base:1';
export type UsagePurposeIndividualRightOperand = string;

export interface UsagePurposeConstraint {
  leftOperand?: 'UsagePurpose';
  operator?: 'isAnyOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | CoreLegalRequirementForThirdPartyRightOperand
      | CoreIndustrycoreRightOperand
      | CoreQualityNotificationsRightOperand
      | CoreDigitalTwinRegistry
      | PfcBaseRightOperand
      | QualityBaseRightOperand
      | DcmBaseRightOperand
      | PurisBaseRightOperand
      | CircularDppRightOperand
      | CircularSmcRightOperand
      | CircularMarketplaceRightOperand
      | CircularMaterialaccountingRightOperand
      | BpdmGateUploadRightOperand
      | BpdmGateDownloadRightOperand
      | BpdmPoolRightOperand
      | BpdmVasDataqualityUploadRightOperand
      | BpdmVasDataqualityDownloadRightOperand
      | BpdmVasCountryrisk
      | BpdmVasBdvUploadRightOperand
      | BpdmVasFpdUploadRightOperand
      | BpdmVasFpdDownloadRightOperand
      | BpdmVasSwdUploadRightOperand
      | BpdmVasSwdDownloadRightOperand
      | BpdmVasNpsUploadRightOperand
      | BpdmVasNpsDownloadRightOperand
      | CcmBaseRightOperand
      | BpdmPoolAllRightOperand
      | LogisticsBaseRightOperand
      | UsagePurposeIndividualRightOperand
    ),
    ...(
      | CoreLegalRequirementForThirdPartyRightOperand
      | CoreIndustrycoreRightOperand
      | CoreQualityNotificationsRightOperand
      | CoreDigitalTwinRegistry
      | PfcBaseRightOperand
      | QualityBaseRightOperand
      | DcmBaseRightOperand
      | PurisBaseRightOperand
      | CircularDppRightOperand
      | CircularSmcRightOperand
      | CircularMarketplaceRightOperand
      | CircularMaterialaccountingRightOperand
      | BpdmGateUploadRightOperand
      | BpdmGateDownloadRightOperand
      | BpdmPoolRightOperand
      | BpdmVasDataqualityUploadRightOperand
      | BpdmVasDataqualityDownloadRightOperand
      | BpdmVasCountryrisk
      | BpdmVasBdvUploadRightOperand
      | BpdmVasFpdUploadRightOperand
      | BpdmVasFpdDownloadRightOperand
      | BpdmVasSwdUploadRightOperand
      | BpdmVasSwdDownloadRightOperand
      | BpdmVasNpsUploadRightOperand
      | BpdmVasNpsDownloadRightOperand
      | CcmBaseRightOperand
      | BpdmPoolAllRightOperand
      | LogisticsBaseRightOperand
      | UsagePurposeIndividualRightOperand
    )[]
  ];
}
