/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UsageRestrictionConstraintSchema = UsageRestrictionConstraint;
export type ThirdPartyForbiddenRightOperand = 'cx.thirdParty.forbidden:1';
export type ManipulationForbiddenRightOperand = 'cx.manipulation.forbidden:1';
export type DerivationsForbiddenRightOperand = 'cx.derivations.forbidden:1';
export type ExtraordinaryAnalyticsForbiddenRightOperand = 'cx.extraordinaryAnalytics.forbidden:1';
export type DataProviderRemovalForbiddenRightOperand = 'cx.dataProviderRemoval.forbidden:1';

export interface UsageRestrictionConstraint {
  leftOperand?: 'UsageRestriction';
  operator?: 'isAllOf';
  /**
   * @minItems 1
   */
  rightOperand?: [
    (
      | ThirdPartyForbiddenRightOperand
      | ManipulationForbiddenRightOperand
      | DerivationsForbiddenRightOperand
      | ExtraordinaryAnalyticsForbiddenRightOperand
      | DataProviderRemovalForbiddenRightOperand
    ),
    ...(
      | ThirdPartyForbiddenRightOperand
      | ManipulationForbiddenRightOperand
      | DerivationsForbiddenRightOperand
      | ExtraordinaryAnalyticsForbiddenRightOperand
      | DataProviderRemovalForbiddenRightOperand
    )[]
  ];
}
