/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type VersionChangesConstraintSchema = VersionChangesConstraint;
export type VersionChangesMinorRightOperand = 'cx.versionChanges.minor:1';
export type VersionChangesMajorRightOperand = 'cx.versionChanges.major:1';

export interface VersionChangesConstraint {
  leftOperand?: 'VersionChanges';
  operator?: 'eq';
  rightOperand?: VersionChangesMinorRightOperand | VersionChangesMajorRightOperand;
}
