/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WarrantyConstraintSchema = WarrantyConstraint;
export type WarrantyNoneRightOperand = 'cx.warranty.none:1';
export type WarrantyContractReferenceRightOperand = 'cx.warranty.contractReference:1';
export type WarrantyDataQualityIssuesRightOperand = 'cx.warranty.dataQualityIssues:1';

export interface WarrantyConstraint {
  leftOperand?: 'Warranty';
  operator?: 'eq';
  rightOperand?:
    | WarrantyNoneRightOperand
    | WarrantyContractReferenceRightOperand
    | WarrantyDataQualityIssuesRightOperand;
}
