/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WarrantyConstraintSchema = WarrantyConstraint;
export type WarrantyContractEndDateRightOperand = 'cx.warranty.contractEndDate:1';

export interface WarrantyConstraint {
  leftOperand?: 'WarrantyDefinition';
  operator?: 'eq';
  rightOperand?: WarrantyContractEndDateRightOperand;
}
