/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WarrantyConstraintSchema = WarrantyConstraint;

export interface WarrantyConstraint {
  leftOperand?: 'Warranty';
  operator?: 'eq';
  rightOperand?:
    | WarrantyNoneRightOperand
    | WarrantyContractReferenceRightOperand
    | WarrantyDataQualityIssuesRightOperand;
}
export interface WarrantyNoneRightOperand {
  const?: 'cx.warranty.none:1';
  legalText?: {
    permission?: 'The provision of the Data is made with the exclusion of any warranty for material defects and defects in title, unless the Data Provider fraudulently conceals such a defect.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface WarrantyContractReferenceRightOperand {
  const?: 'cx.warranty.contractReference:1';
  legalText?: {
    permission?: 'The provision of the Data is subject to the warranty for material defects and defects in title as agreed in the description of the subject matter of performance according to the referenced contract (leftOperand: ContractReference).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
export interface WarrantyDataQualityIssuesRightOperand {
  const?: 'cx.warranty.dataQualityIssues:1';
  legalText?: {
    permission?: 'In the event of a material deviation from the contractually agreed data quality, the Data Provider shall be entitled to (i) demand the rectification of defects by provision of Data in the quality owed, (ii) terminate the contract in the event of failure to remedy the defect, and (iii) claim damages in accordance with the liability provisions set out below.';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
