/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WarrantyDurationConstraintSchema = WarrantyDurationConstraint;

export interface WarrantyDurationConstraint {
  leftOperand?: 'WarrantyDurationMonths';
  operator?: 'eq';
  rightOperand?: WarrantyDurationMonthsRightOperand;
}
export interface WarrantyDurationMonthsRightOperand {
  legalText?: {
    permission?: 'The provision of the Data is subject to a warranty for material and legal defects for a period specified herein in months.';
    [k: string]: unknown;
  };
  operandType?: 'integer';
}
