/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WarrantyConstraintSchema = WarrantyConstraint;

export interface WarrantyConstraint {
  leftOperand?: 'WarrantyDefinition';
  operator?: 'eq';
  rightOperand?: WarrantyContractEndDateRightOperand;
}
export interface WarrantyContractEndDateRightOperand {
  const?: 'cx.warranty.contractEndDate:1';
  legalText?: {
    permission?: 'The provision of the Data is subject to a warranty for material defects and defects in title until the end of the Agreement concluded via the Registered Connector (RC).';
    [k: string]: unknown;
  };
  operandType?: 'string';
}
